FROM debian:9

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends --yes install \
        acl \
        attr \
        autoconf \
        bind9utils \
        bison \
        build-essential \
        debhelper \
        dnsutils \
        docbook-xml \
        docbook-xsl \
        flex \
        gdb \
        libjansson-dev \
        krb5-user \
        libacl1-dev \
        libaio-dev \
        libarchive-dev \
        libattr1-dev \
        libblkid-dev \
        libbsd-dev \
        libcap-dev \
        libcups2-dev \
        libgnutls28-dev \
        libgpgme11-dev \
        libjson-perl \
        libldap2-dev \
        libncurses5-dev \
        libpam0g-dev \
        libparse-yapp-perl \
        libpopt-dev \
        libreadline-dev \
        nettle-dev \
        perl \
        perl-modules \
        pkg-config \
        python-all-dev \
        python-crypto \
        python-dbg \
        python-dev \
        python-dnspython \
        python3-dnspython \
        python-gpgme \
        python3-gpgme \
        python-markdown \
        python3-markdown \
        python3-dev \
        xsltproc \
        zlib1g-dev

ENV GITTAG 4.8.0rc2
