#!/bin/bash -e
backupConfig()
{
if [ ! -d $BACKUPDIR ] ; then
    echo $BACKUPDIR not found did you forget add a volume?
    exit 1
else
    chown timemachine:timemachine $BACKUPDIR
fi
}

if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]] ; then
    backupConfig
    exec $SMBPATH/sbin/smbd --no-process-group --log-stdout --foreground "$@"
else
    exec "$@"
fi
