#!/bin/bash
set -x -e -o pipefail

startPostfix()
{
    echo "======================================================================================="
    echo "=                 Starting Postfix, logs after this are from Postfix                  ="
    echo "======================================================================================="
    exec /usr/lib/postfix/sbin/master -i "$@"
}

if [[ -z ${1} ]] || [[ ${1:0:1} == '-' ]] ; then
    startPostfix "$@"
else
    exec "$@"
fi