version: '3.3'

services:
    transmission:
        image: linuxserver/transmission
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        volumes:
            - /media/transmission/config:/config
            - /media/transmission/torrents:/watch
            - /media/transmission/downloads:/downloads
        restart: always
        environment:
            PGID: 109 
            PUID: 109
            TZ: Europe/Berlin
    mariadb:
        image: linuxserver/mariadb
        ports:
            - 3306:3306
        volumes:
            - /media/kodi/mariadb:/config
        restart: always
        environment:
            PGID: 109 
            PUID: 109
            TZ: Europe/Berlin
    kodi-headless:
        depends_on:
            - mariadb
        image: linuxserver/kodi-headless
        ports:
            - 8080:8080
            - 9777:9777/udp
        volumes:
            - /media/kodi/config:/config/.kodi
        restart: always
        environment:
            PGID: 109 
            PUID: 109
            TZ: Europe/Berlin
    couchpotato:
        depends_on:
            - transmission
        image: linuxserver/couchpotato
        ports:
            - 5050:5050
        volumes:
            - /media/couchpotato/config:/config
            - /media/transmission/downloads:/downloads
            - /media/movies:/movies
        restart: always
        environment:
            PGID: 109 
            PUID: 109
            TZ: Europe/Berlin
    sickrage:
        depends_on:
            - transmission
            - kodi-headless
        image: linuxserver/sickrage
        ports:
            - 8081:8081
        volumes:
            - /media/sickrage/config:/config
            - /media/transmission/downloads:/downloads
            - /media/tv:/tv
        restart: always
        environment:
            PGID: 109 
            PUID: 109
            TZ: Europe/Berlin
