version: '3.3'

networks:
    external:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 192.168.100.1/24
    internal:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.enable_ip_masquerade: "false"
        ipam:
            driver: default
            config:
            - subnet: 192.168.101.1/24
services:
    tor:
        image: dperson/torproxy
        restart: always
        environment:
            GROUPID: 109 
            USERID: 109
            TZ: Europe/Berlin
        networks:
            - internal
            - external
    transmission:
        image: linuxserver/transmission
        ports:
            - 9091:9091
        volumes:
            - /media/transmission/config:/config
            - /media/transmission/torrents:/watch
            - /media/transmission/downloads:/downloads
        restart: always
        environment:
            PGID: 109 
            PUID: 109
            TZ: Europe/Berlin
        networks:
            - internal
    mariadb:
        image: linuxserver/mariadb
        ports:
            - 3306:3306
        volumes:
            - /media/kodi/mariadb:/config
        restart: always
        environment:
            PGID: 109 
            PUID: 109
            TZ: Europe/Berlin
        networks:
            - internal
    kodi-headless:
        image: linuxserver/kodi-headless
        ports:
            - 8080:8080
        volumes:
            - /media/kodi/config:/config/.kodi
        restart: always
        environment:
            PGID: 109 
            PUID: 109
            TZ: Europe/Berlin
        networks:
            - internal
        depends_on:
            - mariadb
    couchpotato:
        depends_on:
            - transmission
        image: linuxserver/couchpotato
        ports:
            - 5050:5050
        volumes:
            - /media/couchpotato/config:/config
            - /media/transmission/downloads:/downloads
            - /media/movies:/movies
        networks:
            - internal
        restart: always
        environment:
            PGID: 109 
            PUID: 109
            TZ: Europe/Berlin
    sickrage:
        depends_on:
            - transmission
            - kodi-headless
        image: linuxserver/sickrage
        ports:
            - 8081:8081
        volumes:
            - /media/sickrage/config:/config
            - /media/transmission/downloads:/downloads
            - /media/tv:/tv
        networks:
            - internal
        restart: always
        environment:
            PGID: 109 
            PUID: 109
            TZ: Europe/Berlin
