#!/bin/bash
set -e -o pipefail

export USER="${USER:-timemachine}"
export PASS="${PASS:-password}"
export PUID="${PUID:-1000}"
export PGID="${PGID:-1000}"
export QUOTA="${QUOTA:-512000}"
export RANDOM_PASS=${RANDOM_PASS:-false}

setPassword()
{
    if [ "$RANDOM_PASS" == true ] ; then
        export PASS=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1)
    fi
}

createUser()
{
    echo "Creating system users"
    getent group timemachine> /dev/null || \
        addgroup -g "$PGID" timemachine
    id -u timemachine > /dev/null || \
        adduser -u "$PUID" -G timemachine -D -h /backups -s /bin/nologin --no-create-home timemachine
    echo "Creating SAMBA user ${USER} with a password of ${PASS}"
    printf "%s\n%s\n" "${PASS}" "${PASS}" | smbpasswd -a -s timemachine
    printf "timemachine = %s" "${USER}" > /etc/samba/users.map
}

checkBackupDir()
{
    printf "Backups will be written to: "
    if ! grep "${BACKUPDIR}" /proc/mounts | awk '{print $1}' ; then
        echo "error volume not found did you forget to add the volume?"
        exit 1
    fi
}

configureQuota()
{
    echo "Setting quote to ${QUOTA}MB"
    QUOTA_IN_BYTES=$((QUOTA * 1048576))
    sed "s%REPLACE_TM_SIZE%${QUOTA_IN_BYTES}%" /etc/samba/smb.conf.tmpl \
      > /etc/samba/smb.conf
    sed "s%REPLACE_TM_SIZE%${QUOTA_IN_BYTES}%" /etc/TimeMachine.quota.tmpl \
      > "${BACKUPDIR}"/.com.apple.TimeMachine.quota.plist

    chown root:root "${BACKUPDIR}"/.com.apple.TimeMachine.quota.plist
    chmod 444 "${BACKUPDIR}"/.com.apple.TimeMachine.quota.plist
}

backupConfig()
{
    echo "Marking ${BACKUPDIR} as supported by timemmachine"
    touch "${BACKUPDIR}"/.com.apple.TimeMachine.supported

    echo "Changing ownership of ${BACKUPDIR} to ${PUID}:${PGID}, this may take a few minutes"
    chown -R "${PUID}":"${PGID}" "${BACKUPDIR}"

    echo "Restricting permissions on ${BACKUPDIR}, this may take a few minutes"
    chmod -R u+rwX,g=,o= "${BACKUPDIR}"
}

startSMB()
{
    echo "==================================================================================="
    echo "=                 Starting SAMBA, logs after this are from SAMBA                  ="
    echo "==================================================================================="
    exec /usr/sbin/smbd --no-process-group --interactive "$@"
}

if [[ -z ${1} ]] || [[ ${1:0:1} == '-' ]] ; then
    echo "Configuring container as a timemachine backup target"
    checkBackupDir
    setPassword
    createUser
    backupConfig
    configureQuota
    startSMB "$@"
else
    exec "$@"
fi