#!/bin/bash -e
export USER=${USER:-timemachine}
export PASS=${PASS:-password}
export PUID=${PUID:-999}
export PGID=${PGID:-999}

setPassword()
{
    if [ $PASS == RANDOM ] ; then
        PASS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)
    fi
}

createUser()
{
    groupadd --gid $PGID timemachine && \
    useradd --uid $PUID --gid $PGID --home /backups --shell /bin/nologin --no-create-home timemachine && \
    echo Setting password of ${USER} to ${PASS}
    printf "$PASS\n$PASS\n" | smbpasswd -a -s ${USER}
    printf "timemachine = $USER" > /etc/samba/users.map
}

backupConfig()
{
    if [ ! -d ${BACKUPDIR} ] ; then
        echo ${BACKUPDIR} not found did you forget to add the volume?
        exit 1
    else
        chown -R ${PUID}:${PGID} ${BACKUPDIR}
        chmod -R u+rwX,g=,o= ${BACKUPDIR}
    fi
}

if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]] ; then
    setPassword
    createUser
    backupConfig
    exec /usr/sbin/smbd --no-process-group --log-stdout --foreground "$@"
else
    exec "$@"
fi
