#!/bin/bash -e
export USER=${USER:-timemachine}
export PASS=${PASS:-password}
export PUID=${PUID:-999}
export PGID=${PGID:-999}

setPassword()
{
    if [ $PASS == RANDOM ] ; then
        PASS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)
    fi
}

createUser()
{
    groupadd --gid $PGID timemachine 
    useradd --uid $PUID --gid $PGID --home /backups --shell /bin/nologin --no-create-home timemachine 
    printf "timemachine = $USER" > /etc/samba/users.map
    echo Setting SAMBA password of ${USER} to ${PASS}
    printf "$PASS\n$PASS\n" | smbpasswd -a -s timemachine
}

checkBackupDir()
{
    if ! grep ${BACKUPDIR} /proc/mounts ; then 
        echo ${BACKUPDIR} volume not found did you forget to add the volume?
        exit 1
    fi
}

backupConfig()
{
    echo Changing ownership of ${BACKUPDIR} to ${PUID}:${PGID}, this may take a few minutes
    chown -R ${PUID}:${PGID} ${BACKUPDIR}
    chmod -R u+rwX,g=,o= ${BACKUPDIR}
}

startSMB()
{
    exec /usr/sbin/smbd --no-process-group --log-stdout --foreground "$@"
}

if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]] ; then
    checkBackupDir
    setPassword
    createUser
    backupConfig
    startSMB
else
    exec "$@"
fi
