#!/bin/bash
set -eu -o pipefail
IMAGE_NAME=samba-timemachine
PLATFORMS="linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7"

build () {
    docker build -t "${IMAGE_NAME}:tmp" -f Dockerfile .
}

_test() {
    build
    bundle install --path vendor/bundle
    bundle exec rspec --format documentation
}

usage() {
  echo "./run test|build|push"
}

push() {
  export DOCKER_CLI_EXPERIMENTAL=enabled
  docker buildx use testbuilder || docker buildx create --name testbuilder
  docker buildx inspect --bootstrap
  docker buildx build \
    --platform "${PLATFORMS}" \
    -t "timjdfletcher/${IMAGE_NAME}:latest" --push .
}

CMD=${1:-}

shift || true
case ${CMD} in
    build) build ;;
    test) _test ;;
    push) push ;;
    *) usage ;;
esac
